trigger:
- master

variables:
- name: slnPath
  value: ./ANPAdmin.sln

jobs:
 - job: Build
   pool:
    vmImage: ubuntu-latest
   steps:
   - bash: |
      dotnet restore $(slnPath)
      dotnet build $(slnPath)



