trigger:
- master

variables:
- name: slnPath
  value: ./ANPAdmin.sln
- name: projPath
  value: ./ANPAdmin.UI/ANPAdmin.UI.csproj
  

jobs:
 - job: Build
   pool:
    vmImage: ubuntu-latest
   steps:
   - bash: |
      dotnet restore $(slnPath)
      dotnet build $(slnPath)
      dotnet publish $(projPath) --configuration Release --output $(Build.ArtifactStagingDirectory)
   - task: PublishBuildArtifacts@1
     inputs:
       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
       ArtifactName: 'drop'
       publishLocation: 'Container'
 
 - job: Deploy_Homolog
   pool:
    vmImage: ubuntu-latest
   dependsOn: Build
   steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'


